ci_logs:
  build_number: '294'
  build_url: https://circleci.com/gh/ackrep-org/ackrep_data/294
commit_logs:
  ackrep_core:
    author: JuliusFiedler
    branch: develop
    date: '2022-08-09 09:32:54'
    message: 'fix: artifact copying'
    sha: 10801ce81bf9a26f43e331b5466acc7268ec39e0
  ackrep_data:
    author: JuliusFiedler
    branch: develop
    date: '2022-08-09 09:56:44'
    message: 'fix: wave eq plotting headless qt problem'
    sha: d235c712c979d708127ec12ce4284e41652a22f8
7WIQH:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <Notebook (pk: 1, key: 7WIQH)> \"(Limit Cycle van der Pol, 10s)\"\
    \n09:59:58 ERROR    \n        The command `jupyter nbconvert --execute --to html\
    \ /code/ackrep_data/notebooks/limit_cycle_vanderPol/notebook.ipynb` exited with\
    \ returncode 1.\n\n        stdout: None\n\n        stderr: None\n        \n\n\
    Calculated with default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 24.6
WV1L5:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 11, key: WV1L5)> \"(controller design via\
    \ LQR for electrical resistance, 10s)\"\n10:00:03 INFO       ... Creating exec-script\
    \ ... \n10:00:03 INFO     execscript-path: /code/ackrep_data/execscript.py\n10:00:03\
    \ INFO       ... running exec-script /code/ackrep_data/execscript.py ... \n10:00:04\
    \ ERROR    \n        The command `python /code/ackrep_data/execscript.py` exited\
    \ with returncode 1.\n\n        stdout: \n\n        stderr: Traceback (most recent\
    \ call last):\n  File \"/code/ackrep_data/problem_solutions/LQR_electrical_resistance/solution.py\"\
    , line 11, in <module>\n    import method_LQR as mlqr  # noqa\n  File \"/code/ackrep_data/method_packages/method_LQR/_build/method_LQR.py\"\
    , line 10, in <module>\n    import control as ctr\n  File \"/opt/conda/lib/python3.8/site-packages/control/__init__.py\"\
    , line 49, in <module>\n    from .bdalg import *\n  File \"/opt/conda/lib/python3.8/site-packages/control/bdalg.py\"\
    , line 57, in <module>\n    from . import xferfcn as tf\n  File \"/opt/conda/lib/python3.8/site-packages/control/xferfcn.py\"\
    , line 56, in <module>\n    from scipy.signal import tf2zpk, zpk2tf, cont2discrete\n\
    ModuleNotFoundError: No module named 'scipy.signal'\n\nDuring handling of the\
    \ above exception, another exception occurred:\n\nTraceback (most recent call\
    \ last):\n  File \"/code/ackrep_data/execscript.py\", line 44, in <module>\n \
    \   import solution\n  File \"/code/ackrep_data/problem_solutions/LQR_electrical_resistance/solution.py\"\
    , line 14, in <module>\n    from method_packages.method_LQR import method_LQR\
    \ as mlqr\nImportError: cannot import name 'method_LQR' from 'method_packages.method_LQR'\
    \ (unknown location)\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 5.8
XRV9G:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 1, key: XRV9G)> \"(controller design via\
    \ LQR for loading bridge, 10s)\"\n10:00:09 INFO       ... Creating exec-script\
    \ ... \n10:00:09 INFO     execscript-path: /code/ackrep_data/execscript.py\n10:00:09\
    \ INFO       ... running exec-script /code/ackrep_data/execscript.py ... \n10:00:12\
    \ ERROR    \n        The command `python /code/ackrep_data/execscript.py` exited\
    \ with returncode 1.\n\n        stdout: \n\n        stderr: * Owlready2 * Warning:\
    \ optimized Cython parser module 'owlready2_optimized' is not available, defaulting\
    \ to slower Python implementation\nTraceback (most recent call last):\n  File\
    \ \"/code/ackrep_data/problem_solutions/LQR_loading_bridge/solution.py\", line\
    \ 11, in <module>\n    import method_LQR as mlqr  # noqa\n  File \"/code/ackrep_data/method_packages/method_LQR/_build/method_LQR.py\"\
    , line 10, in <module>\n    import control as ctr\n  File \"/opt/conda/lib/python3.8/site-packages/control/__init__.py\"\
    , line 49, in <module>\n    from .bdalg import *\n  File \"/opt/conda/lib/python3.8/site-packages/control/bdalg.py\"\
    , line 57, in <module>\n    from . import xferfcn as tf\n  File \"/opt/conda/lib/python3.8/site-packages/control/xferfcn.py\"\
    , line 56, in <module>\n    from scipy.signal import tf2zpk, zpk2tf, cont2discrete\n\
    ModuleNotFoundError: No module named 'scipy.signal'\n\nDuring handling of the\
    \ above exception, another exception occurred:\n\nTraceback (most recent call\
    \ last):\n  File \"/code/ackrep_data/execscript.py\", line 44, in <module>\n \
    \   import solution\n  File \"/code/ackrep_data/problem_solutions/LQR_loading_bridge/solution.py\"\
    , line 14, in <module>\n    from method_packages.method_LQR import method_LQR\
    \ as mlqr\nImportError: cannot import name 'method_LQR' from 'method_packages.method_LQR'\
    \ (unknown location)\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.9
7TWE9:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 4, key: 7TWE9)> \"(controller design via\
    \ LQR for a two mass floating-body system, 10s)\"\n10:00:17 INFO       ... Creating\
    \ exec-script ... \n10:00:17 INFO     execscript-path: /code/ackrep_data/execscript.py\n\
    10:00:17 INFO       ... running exec-script /code/ackrep_data/execscript.py ...\
    \ \n10:00:20 ERROR    \n        The command `python /code/ackrep_data/execscript.py`\
    \ exited with returncode 1.\n\n        stdout: \n\n        stderr: * Owlready2\
    \ * Warning: optimized Cython parser module 'owlready2_optimized' is not available,\
    \ defaulting to slower Python implementation\nTraceback (most recent call last):\n\
    \  File \"/code/ackrep_data/problem_solutions/LQR_two_mass_floating_bodies/solution.py\"\
    , line 11, in <module>\n    import method_LQR as mlqr  # noqa\n  File \"/code/ackrep_data/method_packages/method_LQR/_build/method_LQR.py\"\
    , line 10, in <module>\n    import control as ctr\n  File \"/opt/conda/lib/python3.8/site-packages/control/__init__.py\"\
    , line 49, in <module>\n    from .bdalg import *\n  File \"/opt/conda/lib/python3.8/site-packages/control/bdalg.py\"\
    , line 57, in <module>\n    from . import xferfcn as tf\n  File \"/opt/conda/lib/python3.8/site-packages/control/xferfcn.py\"\
    , line 56, in <module>\n    from scipy.signal import tf2zpk, zpk2tf, cont2discrete\n\
    ModuleNotFoundError: No module named 'scipy.signal'\n\nDuring handling of the\
    \ above exception, another exception occurred:\n\nTraceback (most recent call\
    \ last):\n  File \"/code/ackrep_data/execscript.py\", line 44, in <module>\n \
    \   import solution\n  File \"/code/ackrep_data/problem_solutions/LQR_two_mass_floating_bodies/solution.py\"\
    , line 14, in <module>\n    from method_packages.method_LQR import method_LQR\
    \ as mlqr\nImportError: cannot import name 'method_LQR' from 'method_packages.method_LQR'\
    \ (unknown location)\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.8
8RWMB:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 16, key: 8RWMB)> \"(PVTOL model, 30s)\"\n\
    10:00:24 INFO       ... Creating exec-script ... \n10:00:24 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:00:24 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:00:28 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython parser\
    \ module 'owlready2_optimized' is not available, defaulting to slower Python implementation\n\
    Traceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 40, in <module>\n    import solution\n  File \"/code/ackrep_data/problem_solutions/PVTOL_2_Forces/solution.py\"\
    , line 6, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 8.1
QWRHA:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 20, key: QWRHA)> \"(SINDy for Lotka Volterra\
    \ Model, 15s)\"\n10:00:33 INFO       ... Creating exec-script ... \n10:00:33 INFO\
    \     execscript-path: /code/ackrep_data/execscript.py\n10:00:33 INFO       ...\
    \ running exec-script /code/ackrep_data/execscript.py ... \n10:00:34 ERROR   \
    \ \n        The command `python /code/ackrep_data/execscript.py` exited with returncode\
    \ 1.\n\n        stdout: \n\n        stderr: Traceback (most recent call last):\n\
    \  File \"/code/ackrep_data/execscript.py\", line 39, in <module>\n    import\
    \ problem as ps\n  File \"/code/ackrep_data/problem_specifications/PySINDy_identify_volterra/problem.py\"\
    , line 9, in <module>\n    from scipy.integrate import solve_ivp, odeint\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 5.8
HPICZ:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 15, key: HPICZ)> \"(acrobot swingup with\
    \ pytrajecotry, 30s)\"\n10:00:38 INFO       ... Creating exec-script ... \n10:00:38\
    \ INFO     execscript-path: /code/ackrep_data/execscript.py\n10:00:38 INFO   \
    \    ... running exec-script /code/ackrep_data/execscript.py ... \n10:00:39 ERROR\
    \    \n        The command `python /code/ackrep_data/execscript.py` exited with\
    \ returncode 1.\n\n        stdout: \n\n        stderr: Traceback (most recent\
    \ call last):\n  File \"/code/ackrep_data/execscript.py\", line 41, in <module>\n\
    \    import problem as ps\n  File \"/code/ackrep_data/problem_specifications/acrobot_swingup/problem.py\"\
    , line 2, in <module>\n    from scipy.integrate import odeint\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 5.4
Z7HZY:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 18, key: Z7HZY)> \"(Motion planning for\
    \ closed kinematic chains using a quasistatic approach, 30s)\"\n10:00:44 INFO\
    \       ... Creating exec-script ... \n10:00:44 INFO     execscript-path: /code/ackrep_data/execscript.py\n\
    10:00:44 INFO       ... running exec-script /code/ackrep_data/execscript.py ...\
    \ \n10:00:46 ERROR    \n        The command `python /code/ackrep_data/execscript.py`\
    \ exited with returncode 1.\n\n        stdout: \n\n        stderr: Traceback (most\
    \ recent call last):\n  File \"/code/ackrep_data/execscript.py\", line 40, in\
    \ <module>\n    import solution\n  File \"/code/ackrep_data/problem_solutions/closed_kinematic_chains_quasistatic/solution.py\"\
    , line 6, in <module>\n    import symbtools.visualisation as vt\n  File \"/opt/conda/lib/python3.8/site-packages/symbtools/visualisation.py\"\
    , line 28, in <module>\n    from scipy.optimize import fmin\nImportError: cannot\
    \ import name 'fmin' from 'scipy.optimize' (unknown location)\n\n        \n\n\
    Calculated with default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 6.8
W8WD1:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 8, key: W8WD1)> \"(controller design for\
    \ the brockett-integrator, 35s)\"\n10:00:50 INFO       ... Creating exec-script\
    \ ... \n10:00:50 INFO     execscript-path: /code/ackrep_data/execscript.py\n10:00:50\
    \ INFO       ... running exec-script /code/ackrep_data/execscript.py ... \n10:00:53\
    \ ERROR    \n        The command `python /code/ackrep_data/execscript.py` exited\
    \ with returncode 1.\n\n        stdout: \n\n        stderr: * Owlready2 * Warning:\
    \ optimized Cython parser module 'owlready2_optimized' is not available, defaulting\
    \ to slower Python implementation\nTraceback (most recent call last):\n  File\
    \ \"/code/ackrep_data/problem_solutions/control_brockett_integrator/solution.py\"\
    , line 9, in <module>\n    import method_geometry_inspired_control as mgic  #\
    \ noqa\n  File \"/code/ackrep_data/method_packages/method_geometry_inspired_control/_build/method_geometry_inspired_control.py\"\
    , line 18, in <module>\n    import scipy.integrate\nModuleNotFoundError: No module\
    \ named 'scipy.integrate'\n\nDuring handling of the above exception, another exception\
    \ occurred:\n\nTraceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 42, in <module>\n    import solution\n  File \"/code/ackrep_data/problem_solutions/control_brockett_integrator/solution.py\"\
    , line 11, in <module>\n    from method_packages.method_geometry_inspired_control\
    \ import method_geometry_inspired_control as mgic\nImportError: cannot import\
    \ name 'method_geometry_inspired_control' from 'method_packages.method_geometry_inspired_control'\
    \ (unknown location)\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.6
M4PDA:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 13, key: M4PDA)> \"(controller design via\
    \ coprime decomposition, 10s)\"\n10:00:58 INFO       ... Creating exec-script\
    \ ... \n10:00:58 INFO     execscript-path: /code/ackrep_data/execscript.py\n10:00:58\
    \ INFO       ... running exec-script /code/ackrep_data/execscript.py ... \n10:01:00\
    \ ERROR    \n        The command `python /code/ackrep_data/execscript.py` exited\
    \ with returncode 1.\n\n        stdout: \n\n        stderr: Traceback (most recent\
    \ call last):\n  File \"/code/ackrep_data/execscript.py\", line 44, in <module>\n\
    \    import solution\n  File \"/code/ackrep_data/problem_solutions/coprime_decomposition_controller/solution.py\"\
    , line 15, in <module>\n    import control\n  File \"/opt/conda/lib/python3.8/site-packages/control/__init__.py\"\
    , line 49, in <module>\n    from .bdalg import *\n  File \"/opt/conda/lib/python3.8/site-packages/control/bdalg.py\"\
    , line 57, in <module>\n    from . import xferfcn as tf\n  File \"/opt/conda/lib/python3.8/site-packages/control/xferfcn.py\"\
    , line 56, in <module>\n    from scipy.signal import tf2zpk, zpk2tf, cont2discrete\n\
    ModuleNotFoundError: No module named 'scipy.signal'\n\n        \n\nCalculated\
    \ with default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 6.7
UKJZI:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 9, key: UKJZI)> \"(double integrator transition\
    \ using PyTrajectory, 3s)\"\n10:01:05 INFO       ... Creating exec-script ...\
    \ \n10:01:05 INFO     execscript-path: /code/ackrep_data/execscript.py\n10:01:05\
    \ INFO       ... running exec-script /code/ackrep_data/execscript.py ... \n10:01:05\
    \ ERROR    \n        The command `python /code/ackrep_data/execscript.py` exited\
    \ with returncode 1.\n\n        stdout: \n\n        stderr: Traceback (most recent\
    \ call last):\n  File \"/code/ackrep_data/execscript.py\", line 41, in <module>\n\
    \    import problem as ps\n  File \"/code/ackrep_data/problem_specifications/double_integrator_transition/problem.py\"\
    , line 2, in <module>\n    from scipy.integrate import odeint\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 5.3
ZPPRG:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 2, key: ZPPRG)> \"(controller design via\
    \ full state feedback, 10s)\"\n10:01:10 WARNING  Applying a solution to multiple\
    \ problems is not yet supported. Taking the last one.\n10:01:10 INFO       ...\
    \ Creating exec-script ... \n10:01:10 INFO     execscript-path: /code/ackrep_data/execscript.py\n\
    10:01:10 INFO       ... running exec-script /code/ackrep_data/execscript.py ...\
    \ \n10:01:13 ERROR    \n        The command `python /code/ackrep_data/execscript.py`\
    \ exited with returncode 1.\n\n        stdout: \n\n        stderr: * Owlready2\
    \ * Warning: optimized Cython parser module 'owlready2_optimized' is not available,\
    \ defaulting to slower Python implementation\nTraceback (most recent call last):\n\
    \  File \"/code/ackrep_data/problem_solutions/full_state_feedback/solution.py\"\
    , line 7, in <module>\n    import method_full_state_feedback as ftf  # noqa\n\
    \  File \"/code/ackrep_data/method_packages/full_state_feedback_controller/_build/method_full_state_feedback.py\"\
    , line 10, in <module>\n    import control as ctr\n  File \"/opt/conda/lib/python3.8/site-packages/control/__init__.py\"\
    , line 49, in <module>\n    from .bdalg import *\n  File \"/opt/conda/lib/python3.8/site-packages/control/bdalg.py\"\
    , line 57, in <module>\n    from . import xferfcn as tf\n  File \"/opt/conda/lib/python3.8/site-packages/control/xferfcn.py\"\
    , line 56, in <module>\n    from scipy.signal import tf2zpk, zpk2tf, cont2discrete\n\
    ModuleNotFoundError: No module named 'scipy.signal'\n\nDuring handling of the\
    \ above exception, another exception occurred:\n\nTraceback (most recent call\
    \ last):\n  File \"/code/ackrep_data/execscript.py\", line 44, in <module>\n \
    \   import solution\n  File \"/code/ackrep_data/problem_solutions/full_state_feedback/solution.py\"\
    , line 10, in <module>\n    from method_packages.method_full_state_feedback import\
    \ method_full_state_feedback as ftf\nModuleNotFoundError: No module named 'method_packages.method_full_state_feedback'\n\
    \n        \n\nCalculated with default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 7.9
IWTAE:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 14, key: IWTAE)> \"(full state observer,\
    \ 10s)\"\n10:01:18 WARNING  Applying a solution to multiple problems is not yet\
    \ supported. Taking the last one.\n10:01:18 INFO       ... Creating exec-script\
    \ ... \n10:01:18 INFO     execscript-path: /code/ackrep_data/execscript.py\n10:01:18\
    \ INFO       ... running exec-script /code/ackrep_data/execscript.py ... \n10:01:21\
    \ ERROR    \n        The command `python /code/ackrep_data/execscript.py` exited\
    \ with returncode 1.\n\n        stdout: \n\n        stderr: * Owlready2 * Warning:\
    \ optimized Cython parser module 'owlready2_optimized' is not available, defaulting\
    \ to slower Python implementation\nTraceback (most recent call last):\n  File\
    \ \"/code/ackrep_data/problem_solutions/full_state_observer/solution.py\", line\
    \ 7, in <module>\n    import method_observer_full_reduced as ofr  # noqa\n  File\
    \ \"/code/ackrep_data/method_packages/method_observer_full_reduced/_build/method_observer_full_reduced.py\"\
    , line 12, in <module>\n    import control as ctr\n  File \"/opt/conda/lib/python3.8/site-packages/control/__init__.py\"\
    , line 49, in <module>\n    from .bdalg import *\n  File \"/opt/conda/lib/python3.8/site-packages/control/bdalg.py\"\
    , line 57, in <module>\n    from . import xferfcn as tf\n  File \"/opt/conda/lib/python3.8/site-packages/control/xferfcn.py\"\
    , line 56, in <module>\n    from scipy.signal import tf2zpk, zpk2tf, cont2discrete\n\
    ModuleNotFoundError: No module named 'scipy.signal'\n\nDuring handling of the\
    \ above exception, another exception occurred:\n\nTraceback (most recent call\
    \ last):\n  File \"/code/ackrep_data/execscript.py\", line 44, in <module>\n \
    \   import solution\n  File \"/code/ackrep_data/problem_solutions/full_state_observer/solution.py\"\
    , line 11, in <module>\n    from method_packages.method_observer_full_reduced\
    \ import method_observer_full_reduced as ofr\nImportError: cannot import name\
    \ 'method_observer_full_reduced' from 'method_packages.method_observer_full_reduced'\
    \ (unknown location)\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.8
NRRYR:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 12, key: NRRYR)> \"(linear trajectory planning\
    \ for electrical resistance, 10s)\"\n10:01:26 INFO       ... Creating exec-script\
    \ ... \n10:01:26 INFO     execscript-path: /code/ackrep_data/execscript.py\n10:01:26\
    \ INFO       ... running exec-script /code/ackrep_data/execscript.py ... \n10:01:28\
    \ ERROR    \n        The command `python /code/ackrep_data/execscript.py` exited\
    \ with returncode 1.\n\n        stdout: \n\n        stderr: Traceback (most recent\
    \ call last):\n  File \"/code/ackrep_data/execscript.py\", line 46, in <module>\n\
    \    import solution\n  File \"/code/ackrep_data/problem_solutions/linear_trajectory_electrical_resistance/solution.py\"\
    , line 15, in <module>\n    import control\n  File \"/opt/conda/lib/python3.8/site-packages/control/__init__.py\"\
    , line 49, in <module>\n    from .bdalg import *\n  File \"/opt/conda/lib/python3.8/site-packages/control/bdalg.py\"\
    , line 57, in <module>\n    from . import xferfcn as tf\n  File \"/opt/conda/lib/python3.8/site-packages/control/xferfcn.py\"\
    , line 56, in <module>\n    from scipy.signal import tf2zpk, zpk2tf, cont2discrete\n\
    ModuleNotFoundError: No module named 'scipy.signal'\n\n        \n\nCalculated\
    \ with default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 6.9
JC2OP:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 7, key: JC2OP)> \"(linear trajectory planning\
    \ for a loading bridge with load, 10s)\"\n10:01:33 INFO       ... Creating exec-script\
    \ ... \n10:01:33 INFO     execscript-path: /code/ackrep_data/execscript.py\n10:01:33\
    \ INFO       ... running exec-script /code/ackrep_data/execscript.py ... \n10:01:35\
    \ ERROR    \n        The command `python /code/ackrep_data/execscript.py` exited\
    \ with returncode 1.\n\n        stdout: \n\n        stderr: Traceback (most recent\
    \ call last):\n  File \"/code/ackrep_data/execscript.py\", line 46, in <module>\n\
    \    import solution\n  File \"/code/ackrep_data/problem_solutions/linear_trajectory_loading_bridge/solution.py\"\
    , line 14, in <module>\n    from pyblocksim import *\n  File \"/opt/conda/lib/python3.8/site-packages/pyblocksim/__init__.py\"\
    , line 14, in <module>\n    from .core import s, t, TFBlock, Blockfnc, compute_block_ouptputs,\\\
    \n  File \"/opt/conda/lib/python3.8/site-packages/pyblocksim/core.py\", line 15,\
    \ in <module>\n    import scipy.integrate as integrate\nModuleNotFoundError: No\
    \ module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 6.8
QO8E1:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 19, key: QO8E1)> \"(linear trajectory planning\
    \ for a two mass floating-body system, 10s)\"\n10:01:39 INFO       ... Creating\
    \ exec-script ... \n10:01:39 INFO     execscript-path: /code/ackrep_data/execscript.py\n\
    10:01:39 INFO       ... running exec-script /code/ackrep_data/execscript.py ...\
    \ \n10:01:41 ERROR    \n        The command `python /code/ackrep_data/execscript.py`\
    \ exited with returncode 1.\n\n        stdout: \n\n        stderr: Traceback (most\
    \ recent call last):\n  File \"/code/ackrep_data/execscript.py\", line 46, in\
    \ <module>\n    import solution\n  File \"/code/ackrep_data/problem_solutions/linear_trajectory_two_mass_floating_bodies/solution.py\"\
    , line 15, in <module>\n    import control\n  File \"/opt/conda/lib/python3.8/site-packages/control/__init__.py\"\
    , line 49, in <module>\n    from .bdalg import *\n  File \"/opt/conda/lib/python3.8/site-packages/control/bdalg.py\"\
    , line 57, in <module>\n    from . import xferfcn as tf\n  File \"/opt/conda/lib/python3.8/site-packages/control/xferfcn.py\"\
    , line 56, in <module>\n    from scipy.signal import tf2zpk, zpk2tf, cont2discrete\n\
    ModuleNotFoundError: No module named 'scipy.signal'\n\n        \n\nCalculated\
    \ with default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 6.7
CZKWU:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 10, key: CZKWU)> \"(tracking controller\
    \ design and nonlinear trajectory planning for electrical resistance, 10s)\"\n\
    10:01:46 INFO       ... Creating exec-script ... \n10:01:46 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:01:46 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:01:47 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: Traceback (most recent call last):\n  File \"\
    /code/ackrep_data/execscript.py\", line 41, in <module>\n    import problem as\
    \ ps\n  File \"/code/ackrep_data/problem_specifications/nonlinear_trajectory_electrical_resistance/problem.py\"\
    , line 10, in <module>\n    from symbtools import modeltools as mt\n  File \"\
    /opt/conda/lib/python3.8/site-packages/symbtools/modeltools.py\", line 11, in\
    \ <module>\n    from scipy.optimize import fmin\nImportError: cannot import name\
    \ 'fmin' from 'scipy.optimize' (unknown location)\n\n        \n\nCalculated with\
    \ default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 5.8
04NUJ:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 17, key: 04NUJ)> \"(tracking controller\
    \ design and nonlinear trajectory planning for a two mass floating-body system,\
    \ 10s)\"\n10:01:52 INFO       ... Creating exec-script ... \n10:01:52 INFO   \
    \  execscript-path: /code/ackrep_data/execscript.py\n10:01:52 INFO       ... running\
    \ exec-script /code/ackrep_data/execscript.py ... \n10:01:53 ERROR    \n     \
    \   The command `python /code/ackrep_data/execscript.py` exited with returncode\
    \ 1.\n\n        stdout: \n\n        stderr: Traceback (most recent call last):\n\
    \  File \"/code/ackrep_data/execscript.py\", line 41, in <module>\n    import\
    \ problem as ps\n  File \"/code/ackrep_data/problem_specifications/nonlinear_trajectory_two_mass_floating_bodies/problem.py\"\
    , line 16, in <module>\n    from symbtools import modeltools as mt\n  File \"\
    /opt/conda/lib/python3.8/site-packages/symbtools/modeltools.py\", line 11, in\
    \ <module>\n    from scipy.optimize import fmin\nImportError: cannot import name\
    \ 'fmin' from 'scipy.optimize' (unknown location)\n\n        \n\nCalculated with\
    \ default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 5.8
HOZEE:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 3, key: HOZEE)> \"(PyInduct backstepping\
    \ example, 10s)\"\n10:01:58 INFO       ... Creating exec-script ... \n10:01:58\
    \ INFO     execscript-path: /code/ackrep_data/execscript.py\n10:01:58 INFO   \
    \    ... running exec-script /code/ackrep_data/execscript.py ... \n10:01:59 ERROR\
    \    \n        The command `python /code/ackrep_data/execscript.py` exited with\
    \ returncode 1.\n\n        stdout: \n\n        stderr: Traceback (most recent\
    \ call last):\n  File \"/code/ackrep_data/execscript.py\", line 41, in <module>\n\
    \    import problem as ps\n  File \"/code/ackrep_data/problem_specifications/pyinduct_backstepping_example/problem.py\"\
    , line 5, in <module>\n    import pyinduct as pi\n  File \"/opt/conda/lib/python3.8/site-packages/pyinduct/__init__.py\"\
    , line 15, in <module>\n    from .core import *\n  File \"/opt/conda/lib/python3.8/site-packages/pyinduct/core.py\"\
    , line 13, in <module>\n    from scipy import integrate\nImportError: cannot import\
    \ name 'integrate' from 'scipy' (unknown location)\n\n        \n\nCalculated with\
    \ default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 5.6
AZFKT:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 5, key: AZFKT)> \"(reduced observer design,\
    \ 10s)\"\n10:02:03 INFO       ... Creating exec-script ... \n10:02:03 INFO   \
    \  execscript-path: /code/ackrep_data/execscript.py\n10:02:03 INFO       ... running\
    \ exec-script /code/ackrep_data/execscript.py ... \n10:02:05 ERROR    \n     \
    \   The command `python /code/ackrep_data/execscript.py` exited with returncode\
    \ 1.\n\n        stdout: \n\n        stderr: Traceback (most recent call last):\n\
    \  File \"/code/ackrep_data/execscript.py\", line 44, in <module>\n    import\
    \ solution\n  File \"/code/ackrep_data/problem_solutions/reduced_observer_two_mass_floating_bodies/solution.py\"\
    , line 9, in <module>\n    import method_observer_full_reduced as ofr  # noqa\n\
    \  File \"/code/ackrep_data/method_packages/method_observer_full_reduced/_build/method_observer_full_reduced.py\"\
    , line 12, in <module>\n    import control as ctr\n  File \"/opt/conda/lib/python3.8/site-packages/control/__init__.py\"\
    , line 49, in <module>\n    from .bdalg import *\n  File \"/opt/conda/lib/python3.8/site-packages/control/bdalg.py\"\
    , line 57, in <module>\n    from . import xferfcn as tf\n  File \"/opt/conda/lib/python3.8/site-packages/control/xferfcn.py\"\
    , line 56, in <module>\n    from scipy.signal import tf2zpk, zpk2tf, cont2discrete\n\
    ModuleNotFoundError: No module named 'scipy.signal'\n\n        \n\nCalculated\
    \ with default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 6.6
HRA9W:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <ProblemSolution (pk: 6, key: HRA9W)> \"(Region of Attractivity\
    \ approximation using local adaptive grid refinement, 10s)\"\n10:02:10 INFO  \
    \     ... Creating exec-script ... \n10:02:10 INFO     execscript-path: /code/ackrep_data/execscript.py\n\
    10:02:10 INFO       ... running exec-script /code/ackrep_data/execscript.py ...\
    \ \n10:02:11 ERROR    \n        The command `python /code/ackrep_data/execscript.py`\
    \ exited with returncode 1.\n\n        stdout: \n\n        stderr: Traceback (most\
    \ recent call last):\n  File \"/code/ackrep_data/execscript.py\", line 39, in\
    \ <module>\n    import problem as ps\n  File \"/code/ackrep_data/problem_specifications/roa_van_der_pol/problem.py\"\
    , line 3, in <module>\n    import scipy.integrate as sc_integrate\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 5.4
GKKTM:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 1, key: GKKTM)> \"(Brockett Integrator, 15s)\"\
    \n10:02:15 INFO       ... Creating exec-script ... \n10:02:15 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:02:15 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:02:18 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython parser\
    \ module 'owlready2_optimized' is not available, defaulting to slower Python implementation\n\
    Traceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 36, in <module>\n    import simulation\n  File \"/code/ackrep_data/system_models/brockett_integrator_system/simulation.py\"\
    , line 10, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.7
CK7EX:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 4, key: CK7EX)> \"(Four-bar Linkage, )\"\n10:02:23\
    \ INFO       ... Creating exec-script ... \n10:02:23 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:02:23 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:02:24 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: Traceback (most recent call last):\n  File \"\
    /code/ackrep_data/execscript.py\", line 35, in <module>\n    import system_model\n\
    \  File \"/code/ackrep_data/system_models/four_bar_linkage_system/system_model.py\"\
    , line 9, in <module>\n    import symbtools.modeltools as mt\n  File \"/opt/conda/lib/python3.8/site-packages/symbtools/modeltools.py\"\
    , line 11, in <module>\n    from scipy.optimize import fmin\nImportError: cannot\
    \ import name 'fmin' from 'scipy.optimize' (unknown location)\n\n        \n\n\
    Calculated with default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 5.8
1VY9F:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 9, key: 1VY9F)> \"(Heat Equation, 20s)\"\n10:02:29\
    \ INFO       ... Creating exec-script ... \n10:02:29 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:02:29 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:02:30 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: Traceback (most recent call last):\n  File \"\
    /code/ackrep_data/execscript.py\", line 35, in <module>\n    import system_model\n\
    \  File \"/code/ackrep_data/system_models/heat_equation/system_model.py\", line\
    \ 5, in <module>\n    import pyinduct as pi\n  File \"/opt/conda/lib/python3.8/site-packages/pyinduct/__init__.py\"\
    , line 15, in <module>\n    from .core import *\n  File \"/opt/conda/lib/python3.8/site-packages/pyinduct/core.py\"\
    , line 13, in <module>\n    from scipy import integrate\nImportError: cannot import\
    \ name 'integrate' from 'scipy' (unknown location)\n\n        \n\nCalculated with\
    \ default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 5.9
U6B7N:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 5, key: U6B7N)> \"(Kapitza's Pendulum, 10s)\"\
    \n10:02:35 INFO       ... Creating exec-script ... \n10:02:35 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:02:35 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:02:38 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython parser\
    \ module 'owlready2_optimized' is not available, defaulting to slower Python implementation\n\
    Traceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 36, in <module>\n    import simulation\n  File \"/code/ackrep_data/system_models/kapitzas_pendulum_system/simulation.py\"\
    , line 10, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.9
IG3GA:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 2, key: IG3GA)> \"(Linear Transport System,\
    \ 15s)\"\n10:02:43 INFO       ... Creating exec-script ... \n10:02:43 INFO   \
    \  execscript-path: /code/ackrep_data/execscript.py\n10:02:43 INFO       ... running\
    \ exec-script /code/ackrep_data/execscript.py ... \n10:02:44 ERROR    \n     \
    \   The command `python /code/ackrep_data/execscript.py` exited with returncode\
    \ 1.\n\n        stdout: \n\n        stderr: Traceback (most recent call last):\n\
    \  File \"/code/ackrep_data/execscript.py\", line 35, in <module>\n    import\
    \ system_model\n  File \"/code/ackrep_data/system_models/linear_transport_system/system_model.py\"\
    , line 5, in <module>\n    import pyinduct as pi\n  File \"/opt/conda/lib/python3.8/site-packages/pyinduct/__init__.py\"\
    , line 15, in <module>\n    from .core import *\n  File \"/opt/conda/lib/python3.8/site-packages/pyinduct/core.py\"\
    , line 13, in <module>\n    from scipy import integrate\nImportError: cannot import\
    \ name 'integrate' from 'scipy' (unknown location)\n\n        \n\nCalculated with\
    \ default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 5.9
BID9I:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 7, key: BID9I)> \"(Loading Bridge, 10s)\"\n\
    10:02:49 INFO       ... Creating exec-script ... \n10:02:49 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:02:49 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:02:52 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython parser\
    \ module 'owlready2_optimized' is not available, defaulting to slower Python implementation\n\
    Traceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 36, in <module>\n    import simulation\n  File \"/code/ackrep_data/system_models/loading_bridge_system/simulation.py\"\
    , line 3, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.9
UXMFA:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 14, key: UXMFA)> \"(Lorenz System, 10s)\"\n\
    10:02:56 INFO       ... Creating exec-script ... \n10:02:56 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:02:56 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:03:00 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython parser\
    \ module 'owlready2_optimized' is not available, defaulting to slower Python implementation\n\
    Traceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 36, in <module>\n    import simulation\n  File \"/code/ackrep_data/system_models/lorenz_system/simulation.py\"\
    , line 10, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.8
DRZGT:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 6, key: DRZGT)> \"(Lotka Volterra, 10s)\"\n\
    10:03:04 INFO       ... Creating exec-script ... \n10:03:04 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:03:04 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:03:07 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython parser\
    \ module 'owlready2_optimized' is not available, defaulting to slower Python implementation\n\
    Traceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 36, in <module>\n    import simulation\n  File \"/code/ackrep_data/system_models/lotka_volterra/simulation.py\"\
    , line 4, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.8
YHS5B:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 8, key: YHS5B)> \"(Modular Multilevel Converters\
    \ (MMC), 50s)\"\n10:03:12 INFO       ... Creating exec-script ... \n10:03:12 INFO\
    \     execscript-path: /code/ackrep_data/execscript.py\n10:03:12 INFO       ...\
    \ running exec-script /code/ackrep_data/execscript.py ... \n10:03:15 ERROR   \
    \ \n        The command `python /code/ackrep_data/execscript.py` exited with returncode\
    \ 1.\n\n        stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython\
    \ parser module 'owlready2_optimized' is not available, defaulting to slower Python\
    \ implementation\nTraceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 36, in <module>\n    import simulation\n  File \"/code/ackrep_data/system_models/mmc_system/simulation.py\"\
    , line 3, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.9
CAS0M:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 12, key: CAS0M)> \"(N Integrator Chain, 10s)\"\
    \n10:03:20 INFO       ... Creating exec-script ... \n10:03:20 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:03:20 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:03:23 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython parser\
    \ module 'owlready2_optimized' is not available, defaulting to slower Python implementation\n\
    Traceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 36, in <module>\n    import simulation\n  File \"/code/ackrep_data/system_models/n_integrator_chain_system/simulation.py\"\
    , line 10, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.6
OHW5Z:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 13, key: OHW5Z)> \"(PVTOL with 2 forces, 15s)\"\
    \n10:03:27 INFO       ... Creating exec-script ... \n10:03:27 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:03:27 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:03:31 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython parser\
    \ module 'owlready2_optimized' is not available, defaulting to slower Python implementation\n\
    Traceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 36, in <module>\n    import simulation\n  File \"/code/ackrep_data/system_models/pvtol_system/simulation.py\"\
    , line 3, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.8
FD5RW:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 3, key: FD5RW)> \"(Roessler Attractor, 10s)\"\
    \n10:03:35 INFO       ... Creating exec-script ... \n10:03:35 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:03:35 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:03:38 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython parser\
    \ module 'owlready2_optimized' is not available, defaulting to slower Python implementation\n\
    Traceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 36, in <module>\n    import simulation\n  File \"/code/ackrep_data/system_models/roessler_attractor_system/simulation.py\"\
    , line 10, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.8
OV6ND:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 11, key: OV6ND)> \"(Stable PTn System, 10s)\"\
    \n10:03:43 INFO       ... Creating exec-script ... \n10:03:43 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:03:43 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:03:46 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython parser\
    \ module 'owlready2_optimized' is not available, defaulting to slower Python implementation\n\
    Traceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 36, in <module>\n    import simulation\n  File \"/code/ackrep_data/system_models/stable_pt_n_system/simulation.py\"\
    , line 10, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.9
AJ0PV:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 15, key: AJ0PV)> \"(Two Mass Floating Bodies,\
    \ 10s)\"\n10:03:51 INFO       ... Creating exec-script ... \n10:03:51 INFO   \
    \  execscript-path: /code/ackrep_data/execscript.py\n10:03:51 INFO       ... running\
    \ exec-script /code/ackrep_data/execscript.py ... \n10:03:54 ERROR    \n     \
    \   The command `python /code/ackrep_data/execscript.py` exited with returncode\
    \ 1.\n\n        stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython\
    \ parser module 'owlready2_optimized' is not available, defaulting to slower Python\
    \ implementation\nTraceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 36, in <module>\n    import simulation\n  File \"/code/ackrep_data/system_models/two_mass_floating_bodies_system/simulation.py\"\
    , line 3, in <module>\n    from scipy.integrate import solve_ivp\nModuleNotFoundError:\
    \ No module named 'scipy.integrate'\n\n        \n\nCalculated with default_conda_environment:0.1.8\n\
    \nFail.\n"
  result: 1
  runtime: 7.8
IKNYP:
  date: '2022-08-09 09:59:34'
  env_version: default_conda_environment:0.1.8
  issues: "Checking <SystemModel (pk: 10, key: IKNYP)> \"(Wave Equation 1D, 20s)\"\
    \n10:03:59 INFO       ... Creating exec-script ... \n10:03:59 INFO     execscript-path:\
    \ /code/ackrep_data/execscript.py\n10:03:59 INFO       ... running exec-script\
    \ /code/ackrep_data/execscript.py ... \n10:04:00 ERROR    \n        The command\
    \ `python /code/ackrep_data/execscript.py` exited with returncode 1.\n\n     \
    \   stdout: \n\n        stderr: Traceback (most recent call last):\n  File \"\
    /code/ackrep_data/execscript.py\", line 35, in <module>\n    import system_model\n\
    \  File \"/code/ackrep_data/system_models/wave_equation/system_model.py\", line\
    \ 5, in <module>\n    import pyinduct as pi\n  File \"/opt/conda/lib/python3.8/site-packages/pyinduct/__init__.py\"\
    , line 15, in <module>\n    from .core import *\n  File \"/opt/conda/lib/python3.8/site-packages/pyinduct/core.py\"\
    , line 13, in <module>\n    from scipy import integrate\nImportError: cannot import\
    \ name 'integrate' from 'scipy' (unknown location)\n\n        \n\nCalculated with\
    \ default_conda_environment:0.1.8\n\nFail.\n"
  result: 1
  runtime: 6.0
