ci_logs:
  build_number: '281'
  build_url: https://circleci.com/gh/ackrep-org/ackrep_data/281
commit_logs:
  ackrep_core:
    author: JuliusFiedler
    branch: develop
    date: '2022-07-22 11:55:39'
    message: 'feat: timeout entity check, smarter version of docker stop'
    sha: a23d8edbbb7216ee1160878f76f79f2dcfc043ed
  ackrep_data:
    author: JuliusFiedler
    branch: develop
    date: '2022-08-05 11:24:45'
    message: 'feat: sindy_ident_volterra added'
    sha: 8fc738c052f2d0a5eac248d2944f33ba5abf4a65
7WIQH:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 27.6
WV1L5:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.0
XRV9G:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.1
7TWE9:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.4
8RWMB:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 12.5
QWRHA:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: "Checking <ProblemSolution (pk: 20, key: QWRHA)> \"(SINDy for Lotka Volterra\
    \ Model, 10s)\"\n11:27:08 INFO       ... Creating exec-script ... \n11:27:08 INFO\
    \     execscript-path: /code/ackrep_data/execscript.py\n11:27:08 INFO       ...\
    \ running exec-script /code/ackrep_data/execscript.py ... \n11:27:11 ERROR   \
    \ \n        The command `python /code/ackrep_data/execscript.py` exited with returncode\
    \ 1.\n\n        stdout: \n\n        stderr: * Owlready2 * Warning: optimized Cython\
    \ parser module 'owlready2_optimized' is not available, defaulting to slower Python\
    \ implementation\nTraceback (most recent call last):\n  File \"/code/ackrep_data/execscript.py\"\
    , line 40, in <module>\n    import solution\n  File \"/code/ackrep_data/problem_solutions/PySINDy_identify_volterra/solution.py\"\
    , line 4, in <module>\n    from click import style\nModuleNotFoundError: No module\
    \ named 'click'\n\n        \n\nCalculated with default_conda_environment:0.1.6\n\
    \nFail.\n"
  result: 1
  runtime: 7.8
HPICZ:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 24.5
Z7HZY:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 25.3
W8WD1:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: "Checking <ProblemSolution (pk: 8, key: W8WD1)> \"(controller design for\
    \ the brockett-integrator, 35s)\"\n11:28:06 INFO       ... Creating exec-script\
    \ ... \n11:28:06 INFO     execscript-path: /code/ackrep_data/execscript.py\n11:28:06\
    \ INFO       ... running exec-script /code/ackrep_data/execscript.py ... \n11:31:06\
    \ ERROR    Entity calculation reached timeout (180s).\n\nCalculated with default_conda_environment:0.1.6\n\
    \nFail.\n"
  result: 1
  runtime: 184.5
M4PDA:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.1
UKJZI:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.0
ZPPRG:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.2
IWTAE:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.2
NRRYR:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.4
JC2OP:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.7
QO8E1:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.9
CZKWU:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.6
04NUJ:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 16.1
HOZEE:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 18.7
AZFKT:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.2
HRA9W:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 11.9
GKKTM:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 12.0
CK7EX:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 15.4
1VY9F:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 14.0
U6B7N:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.0
IG3GA:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 11.2
BID9I:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 8.5
UXMFA:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 8.3
DRZGT:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 8.2
YHS5B:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 61.9
CAS0M:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 8.2
OHW5Z:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 15.2
FD5RW:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 8.5
OV6ND:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 9.2
AJ0PV:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 8.3
IKNYP:
  date: '2022-08-05 11:25:55'
  env_version: default_conda_environment:0.1.6
  issues: ''
  result: 0
  runtime: 16.2
